GET http://localhost:8080/spring-oauth-auth-server/oauth/authorize?client_id=webapp-client&response_type=code&redirect_uri=http://localhost:8080/spring-oauth-auth-server HTTP/1.1
Authorization: Basic dGVzdGU6MTIz